let mode='quiz', score=0, streak=0, misses=JSON.parse(localStorage.getItem('d491_master_misses')||'[]');
let quizDeck=[], quizIndex=0, quizAnswered=false, matchSet=[], selected=null, matched=0, missIndex=0, missAnswered=false;
const $=id=>document.getElementById(id);
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;")}
function saveMisses(){localStorage.setItem('d491_master_misses',JSON.stringify(misses));$('missCount').textContent=misses.length;$('missPill').textContent=misses.length+' misses'}
function addMiss(c){if(!misses.some(x=>x.id===c.id)){misses.push(c);saveMisses()}} function removeMiss(c){misses=misses.filter(x=>x.id!==c.id);saveMisses()}
function setScore(n){score+=n;$('score').textContent=score;if(score>0&&score%10===0)showCelebrate()} function setStreak(n){streak=n;$('streak').textContent=streak}
function showCelebrate(){$('celebration').classList.add('show')} function closeCelebration(){$('celebration').classList.remove('show')}
function pool(){let c=$('category').value;let p=c==='all'?QUESTIONS:QUESTIONS.filter(x=>x.cat===c);return p.length?p:QUESTIONS}
function setupCats(){let sel=$('category');sel.innerHTML='<option value="all">Todo mezclado</option>';CATS.forEach(c=>{let o=document.createElement('option');o.textContent=c;sel.appendChild(o)})}
function showMode(m,btn){mode=m;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');['quiz','match','misses','review','keywords'].forEach(x=>$(x+'Mode').classList.toggle('hidden',x!==m));restartMode()}
function restartMode(){if(mode==='quiz')startQuiz();if(mode==='match')newMatchRound();if(mode==='misses')renderMiss();if(mode==='review')renderReview();if(mode==='keywords')renderKeywords()}
function answerBlock(c){return `<div class="ebox"><b>Answer in English:</b> ${esc(c.a)}<br><b>Respuesta en español:</b> ${esc(c.a)}<br><br><b>Real scenario:</b> ${esc(c.real)}<br><br><b>Short explanation EN:</b> ${esc(c.en)}<br><b>Explicación ES:</b> ${esc(c.es)}</div><div class="kbox"><b>Keywords:</b> ${esc(c.keys)}</div>${c.trap?'<div class="kbox"><b>Trap:</b> '+esc(c.trap)+'</div>':''}`}
function startQuiz(){quizDeck=shuffle(pool());quizIndex=0;renderQuiz()} function currentQ(){return quizDeck[quizIndex%quizDeck.length]}
function renderQuiz(){quizAnswered=false;let c=currentQ();$('qCat').textContent=c.cat;$('qText').textContent=c.q;$('quizCounter').textContent=(quizIndex+1)+' / '+quizDeck.length;$('quizProgress').style.width=((quizIndex+1)/quizDeck.length*100)+'%';$('quizFeedback').className='feedback';let opts=shuffle(c.options);$('choices').innerHTML='';opts.forEach((o,i)=>{let b=document.createElement('button');b.className='choice';b.innerHTML=`<span class="badge">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span>`;b.onclick=()=>checkQ(o,b,c);$('choices').appendChild(b)})}
function checkQ(ans,btn,c){if(quizAnswered)return;quizAnswered=true;document.querySelectorAll('#choices .choice').forEach(b=>{let t=b.innerText.replace(/^[A-D]\s*/,'').trim();if(t===c.a)b.classList.add('correct')});let ok=ans===c.a;if(ok){setScore(1);setStreak(streak+1);btn.classList.add('correct');removeMiss(c)}else{setStreak(0);btn.classList.add('wrong');addMiss(c)}let f=$('quizFeedback');f.className='feedback show '+(ok?'good':'bad');f.innerHTML=(ok?'✅ Correct!':'❌ Missed. Saved to misses.')+answerBlock(c)}
function nextQ(){quizIndex=(quizIndex+1)%quizDeck.length;renderQuiz()} function prevQ(){quizIndex=(quizIndex-1+quizDeck.length)%quizDeck.length;renderQuiz()} function quizHint(){let c=currentQ();let f=$('quizFeedback');f.className='feedback show hint';f.innerHTML='💡 '+esc(c.keys)}
function newMatchRound(){matchSet=shuffle(pool()).slice(0,10);matched=0;selected=null;$('matchProgress').style.width='0%';$('matchCounter').textContent='0 / '+matchSet.length+' matches';$('matchFeedback').className='feedback';renderMatch()}
function renderMatch(){$('leftCards').innerHTML='';$('rightCards').innerHTML='';shuffle(matchSet).forEach(c=>{let d=document.createElement('div');d.className='card';d.dataset.id=c.id;d.textContent=c.q;d.onclick=()=>selectLeft(d);$('leftCards').appendChild(d)});shuffle(matchSet).forEach(c=>{let d=document.createElement('div');d.className='card';d.dataset.id=c.id;d.textContent=c.a;d.onclick=()=>selectRight(d,c);$('rightCards').appendChild(d)})}
function selectLeft(el){if(el.classList.contains('done'))return;document.querySelectorAll('#leftCards .card').forEach(x=>x.classList.remove('selected'));selected=el;el.classList.add('selected')}
function selectRight(el,c){if(!selected||el.classList.contains('done'))return;let ok=selected.dataset.id===el.dataset.id;if(ok){selected.classList.add('done');el.classList.add('done');matched++;setScore(1);setStreak(streak+1);removeMiss(c);$('matchProgress').style.width=(matched/matchSet.length*100)+'%';$('matchCounter').textContent=matched+' / '+matchSet.length+' matches';if(matched===matchSet.length)showCelebrate();let f=$('matchFeedback');f.className='feedback show good';f.innerHTML='✅ Correct match!'+answerBlock(c)}else{setStreak(0);addMiss(matchSet.find(x=>x.id==selected.dataset.id));el.classList.add('wrongFlash');selected.classList.add('wrongFlash');setTimeout(()=>{el.classList.remove('wrongFlash');if(selected)selected.classList.remove('wrongFlash')},500);let f=$('matchFeedback');f.className='feedback show bad';f.innerHTML='❌ Casi. La guardé en misses.'}selected=null;document.querySelectorAll('#leftCards .card').forEach(x=>x.classList.remove('selected'))}
function matchHint(){let c=matchSet.find(x=>!document.querySelector('#rightCards .card.done[data-id="'+x.id+'"]'));if(!c)return;let f=$('matchFeedback');f.className='feedback show hint';f.innerHTML='👀 <b>Hint:</b> '+esc(c.keys)+'<div class="ebox">Answer: '+esc(c.a)+'</div>'}
function renderMiss(){missAnswered=false;if(!misses.length){$('missText').textContent='No misses yet.';$('missChoices').innerHTML='';$('missFeedback').className='feedback';saveMisses();return}let c=misses[missIndex%misses.length];$('missText').textContent=c.q;$('missFeedback').className='feedback';let opts=shuffle(c.options);$('missChoices').innerHTML='';opts.forEach((o,i)=>{let b=document.createElement('button');b.className='choice';b.innerHTML=`<span class="badge">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span>`;b.onclick=()=>checkMiss(o,b,c);$('missChoices').appendChild(b)});saveMisses()}
function checkMiss(ans,btn,c){if(missAnswered)return;missAnswered=true;let ok=ans===c.a;document.querySelectorAll('#missChoices .choice').forEach(b=>{let t=b.innerText.replace(/^[A-D]\s*/,'').trim();if(t===c.a)b.classList.add('correct')});if(ok){btn.classList.add('correct');setScore(1);setStreak(streak+1);removeMiss(c)}else{btn.classList.add('wrong');setStreak(0)}let f=$('missFeedback');f.className='feedback show '+(ok?'good':'bad');f.innerHTML=(ok?'✅ Removed from misses.':'❌ Still missed.')+answerBlock(c)}
function nextMiss(){if(misses.length)missIndex=(missIndex+1)%misses.length;renderMiss()} function clearMisses(){if(confirm('Clear all misses?')){misses=[];saveMisses();renderMiss()}}
function renderReview(){let div=$('reviewList');div.innerHTML='';pool().forEach(c=>{let d=document.createElement('div');d.className='reviewItem';d.innerHTML='<span class="tag">'+esc(c.cat)+'</span><br><b>'+esc(c.q)+'</b><br><br>✅ <b>'+esc(c.a)+'</b>'+answerBlock(c);div.appendChild(d)})}
function renderKeywords(){let items=[['cause / why','Diagnostic analytics'],['most likely / future','Predictive analytics'],['best strategy / optimal / should','Prescriptive analytics'],['what happened / most popular','Descriptive analytics'],['purchased together','Association rules / Market Basket'],['random sample / self-reported','Bias / representativeness'],['time frame / updated','Timeliness'],['button color / two versions','A/B test'],['binary / yes-no','Logistic regression'],['outliers / quartiles','Box plot'],['over time','Line chart'],['relationship between two numbers','Scatterplot']];let div=$('keywordGrid');div.innerHTML='';items.forEach(([k,a])=>{let d=document.createElement('div');d.className='keyword';d.innerHTML='<b>'+esc(k)+'</b><br>→ '+esc(a);div.appendChild(d)})}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>showMode(b.dataset.mode,b)));
$('newRound').onclick=restartMode;$('clearMisses').onclick=clearMisses;$('nextQ').onclick=nextQ;$('prevQ').onclick=prevQ;$('hintQ').onclick=quizHint;$('nextMatch').onclick=newMatchRound;$('matchHint').onclick=matchHint;$('nextMiss').onclick=nextMiss;$('closeCelebration').onclick=closeCelebration;$('category').onchange=restartMode;
setupCats();saveMisses();startQuiz();newMatchRound();renderReview();renderKeywords();
